In [1]:
import numpy as np

In [72]:
def pinv(A):
    m,n = A.shape
    U,d,VT = np.linalg.svd(A)
    Dp = np.zeros((n,m))
    np.fill_diagonal(Dp, 1/d)
    A1 = VT.T @ Dp @ U.T
    A2 = np.linalg.pinv(A) 
    print("Below is the p-inv that we implemented")
    print(A1)
    print()
    print("Below is the p-inv that python implemented as a reference.")
    print(A2)

In [73]:
np.random.seed(0)
X=np.random.random((4,3))
pinv(X)

Below is the p-inv that we implemented
[[ 1.85535278  1.87971205 -2.48421247  0.11629795]
 [ 0.64924668 -1.80836698 -0.25265679  1.92882814]
 [-1.56367236  0.89214727  2.36921043 -1.73347873]]

Below is the p-inv that python implemented as a reference.
[[ 1.85535278  1.87971205 -2.48421247  0.11629795]
 [ 0.64924668 -1.80836698 -0.25265679  1.92882814]
 [-1.56367236  0.89214727  2.36921043 -1.73347873]]
